### ISSUE TITLE
[feature] print less path

### ISSUE THREAD

**Issue by holmanb** [mdmintz/pdbp#62]
Default behavior is to print the full path to a source file, but this adds unnecessary information in most cases. I know that this is default behavior that is expected from pdb / pdbpp, but I'd love to be able to set a configuration to have pdbp find the root of the project and, if found, only report the path under root directory of a project.

From the picture on the main page I want to see:

```
> SeleniumBase/examples/test_mfa_login.py(9)
```

Maybe this would even be a reasonable default? Increasing signal to noise ratio when debugging always seems helpful to me.

**Comment by mdmintz** [comment]
Not sure if there's a good way to determine the path to the root of the project directory, especially since you could have project directories inside of other project directories.

If regular `pdb` had an option for this, I could probably include it. But since that full path is the current default behavior of regular `pdb`, I probably wouldn't want to change that behavior in `pdbp`.

**Comment by mdmintz** [comment]
However, replacing the HOME DIR with `~` is easy to do, if that's good enough:

<img width="760" alt="Screenshot 2024-06-28 at 5 29 00 PM" src="https://github.com/mdmintz/pdbp/assets/6788579/d89d8aa7-d900-4c93-9526-962e26a60cb5">

**Comment by mdmintz** [comment]
This was resolved in `1.5.1` - https://github.com/mdmintz/pdbp/releases/tag/v1.5.1

(The `$HOME` directory in the path gets replaced with a `~`)
